import * as _ from 'ionicons/icons';

export default {
  check: _.checkmarkOutline,
  checkCircle: _.checkmarkCircleOutline,
  checkDone: _.checkmarkDoneOutline,
  alarm: _.alarmOutline,
  add: _.addOutline,
  addCircle: _.addCircle,
  filter: _.filterSharp,
  search: _.searchSharp,
  searchCircle: _.searchCircleOutline,
  trash: _.trashOutline,
  trashBin: _.trashBinOutline,
  arrowUndo: _.arrowUndoCircleOutline,
  settings: _.settingsOutline,
  language: _.languageOutline,
  reader: _.readerOutline,
  albums: _.albumsOutline,
  radio: _.radioOutline,
  volume: _.volumeMediumOutline,
  alert: _.alertCircleOutline,
  return: _.returnUpBackOutline,
  swapVertical: _.swapVerticalOutline,
  caretForward: _.caretForwardOutline,
  caretBack: _.caretBackOutline,
  caretUpCircle: _.caretUpCircleOutline,
  ellipsisVertical: _.ellipsisVertical,
  closeCircle: _.closeCircleOutline,
  close: _.closeOutline,
  save: _.saveOutline,
  pencil: _.pencilOutline,
  mail: _.mailOutline,
  share: _.shareSocialOutline,
  star: _.starOutline,
  information: _.informationCircleOutline,
  power: _.powerOutline,

  chevronDown: _.chevronDown,
  chevronUp: _.chevronUp,
  ellipse: _.ellipse,
  sunny: _.sunny,
  moon: _.moon,
  funnel: _.funnel,
}